[workspace]
name = "ufo"
authors = ["Daniel Duberg"]
channels = ["https://prefix.dev/conda-forge"]
description = "UFO"
homepage = "https://github.com/UnknownFreeOccupied/ufo"
license = "BSD-3-Clause"
platforms = [
	"linux-64", 
	"linux-aarch64", 
	"osx-arm64", 
	"win-64"
]
readme = "README.md"
repository = "https://github.com/UnknownFreeOccupied/ufo"
version = "0.1.0"
requires-pixi = ">=0.55.0"

[dependencies]
cmake = ">=4.2.3,<5"
catch2 = ">=3.13.0,<4"
tbb = ">=2022.3.0,<2023"
doxygen = ">=1.13.2,<2"
ninja = ">=1.13.2,<2"
# clang = ">=21.1.8,<22"
clang-format = ">=21.1.8,<22"
clang-tools = ">=21.1.8,<22"
# git = ">=2.53.0,<3"
# sed = ">=4.9,<5"

[tasks]
format = { cmd = "scripts/format.bash" }
format-all = { cmd = "scripts/format_all.bash" }
test = { cmd = "scripts/test.sh" }
